visitantes/src/app/log-in/log-in.component.html
=> Cambie nombre login

visitantes/src/app/informes/informes.component.css, visitantes/src/app/informes/informes.component.html, visitantes/src/index.html, visitantes/src/styles.css
Se creo un avance de la pantalla que se estara utilizando en la seccion Informes:Admin
=> Creacion de pantalla de informes

visitantes/src/app/visita-guardia/visita-guardia.component.css, visitantes/src/app/visita-guardia/visita-guardia.component.html
=> Estructura de pantalla de Visitantes Guardias

visitantes/src/app/visita-guardia/visita-guardia.component.css, visitantes/src/app/visita-guardia/visita-guardia.component.html
=> Modificacion dimensiones VisitaGuardia

visitantes/src/app/bajas/bajas.component.css, visitantes/src/app/bajas/bajas.component.html
Se realizo el dise;o para el modulo de bajas por parte del administrador
=> se realizo el dise;o para el modulo de bajas

visitantes/src/app/registrar-salida/registrar-salida.component.css, visitantes/src/app/registrar-salida/registrar-salida.component.html
Aceptenla porfis esta bien eso creo uwu
=> Pagina de registro de Salida

visitantes/src/app/registrar-agenda/registrar-agenda.component.css, visitantes/src/app/registrar-agenda/registrar-agenda.component.html
Me lo aceptan otra vez por fiii uwu
=> Pagina de registro Agendados

visitantes/src/app/entregar-paquete/entregar-paquete.component.css, visitantes/src/app/entregar-paquete/entregar-paquete.component.html, visitantes/src/app/registrar-agenda/registrar-agenda.component.html
Soybyo de nuevo lo aceptan ? uwu
=> Pagina de entrega de Paquetes

visitantes/src/app/altas-modificaciones/altas-modificaciones.component.html, visitantes/src/app/app.module.ts, visitantes/src/app/bajas/bajas.component.html, visitantes/src/app/bitacora-trabajadores/bitacora-trabajadores.component.html, visitantes/src/app/entregar-paquete/entregar-paquete.component.html, visitantes/src/app/menu-agenda/menu-agenda.component.css, visitantes/src/app/menu-agenda/menu-agenda.component.html, visitantes/src/app/menu-agenda/menu-agenda.component.spec.ts, visitantes/src/app/menu-agenda/menu-agenda.component.ts, visitantes/src/app/menu-global/menu-global.component.css, visitantes/src/app/menu-global/menu-global.component.html, visitantes/src/app/menu-global/menu-global.component.spec.ts, visitantes/src/app/menu-global/menu-global.component.ts, visitantes/src/app/visita-condomino/visita-condomino.component.css, visitantes/src/app/visita-condomino/visita-condomino.component.html
=> Se agrego barras y nueva pantalla

visitantes/src/app/app.component.css, visitantes/src/app/bajas/bajas.component.html
=> Se agrego el estiloa app.components

visitantes/src/app/components/agenda-condomino/agenda-condomino.component.spec.ts, visitantes/src/app/components/altas-modificaciones/altas-modificaciones.component.html, visitantes/src/app/components/altas-modificaciones/altas-modificaciones.component.ts, visitantes/src/app/components/bajas/bajas.component.html, visitantes/src/app/components/bajas/bajas.component.spec.ts, visitantes/src/app/components/bitacora-trabajadores/bitacora-trabajadores.component.html, visitantes/src/app/components/bitacora-trabajadores/bitacora-trabajadores.component.spec.ts, visitantes/src/app/components/entregar-paquete/entregar-paquete.component.html, visitantes/src/app/components/entregar-paquete/entregar-paquete.component.spec.ts, visitantes/src/app/components/informes/informes.component.html, visitantes/src/app/components/menu-global/menu-global.component.css, visitantes/src/app/components/menu-global/menu-global.component.html, visitantes/src/app/components/pagos/pagos.component.html, visitantes/src/app/components/pagos/pagos.component.ts, visitantes/src/app/components/pie-pagina/pie-pagina.component.css, visitantes/src/app/components/registrar-agenda/registrar-agenda.component.html, visitantes/src/app/components/registrar-agenda/registrar-agenda.component.spec.ts, visitantes/src/app/components/registrar-paqueteria/registrar-paqueteria.component.html, visitantes/src/app/components/registrar-paqueteria/registrar-paqueteria.component.ts, visitantes/src/app/components/registrar-salida/registrar-salida.component.html, visitantes/src/app/components/registrar-salida/registrar-salida.component.spec.ts, visitantes/src/app/components/trabajador/trabajador.component.html, visitantes/src/app/components/trabajador/trabajador.component.ts, visitantes/src/app/components/visita-condomino/visita-condomino.component.html, visitantes/src/app/components/visita-condomino/visita-condomino.component.ts, visitantes/src/app/components/visita-guardia/visita-guardia.component.css, visitantes/src/app/components/visita-guardia/visita-guardia.component.html, visitantes/src/app/components/visita-guardia/visita-guardia.component.spec.ts
Se arreglo el menu bar y arreglo de pantallas
=> Arreglo CSS

visitantes/src/app/components/bitacora-trabajadores/bitacora-trabajadores.component.ts, visitantes/src/app/components/entregar-paquete/entregar-paquete.component.css, visitantes/src/app/components/entregar-paquete/entregar-paquete.component.html, visitantes/src/app/components/entregar-paquete/entregar-paquete.component.spec.ts, visitantes/src/app/components/entregar-paquete/entregar-paquete.component.ts, visitantes/src/app/components/registrar-paqueteria/registrar-paqueteria.component.css, visitantes/src/app/components/trabajador/trabajador.component.ts
Se agregaron las alerta sde las pantallas solicitadas, se inicio la programacion de la pantalla bitacora de trabajadores (aun esta en proceso de desarrollo)
=> agregado de alertas

visitantes/src/app/app.component.html, visitantes/src/app/components/altas/altas.component.css, visitantes/src/app/components/altas/altas.component.html, visitantes/src/app/components/bajas/bajas.component.html, visitantes/src/app/components/bitacora-trabajadores/bitacora-trabajadores.component.html, visitantes/src/app/components/encabezado/encabezado.component.html, visitantes/src/app/components/entregar-paquete/entregar-paquete.component.html, visitantes/src/app/components/informes/informes.component.html, visitantes/src/app/components/menu-global/menu-global.component.css, visitantes/src/app/components/menu-global/menu-global.component.html, visitantes/src/app/components/modificaciones/modificaciones.component.html, visitantes/src/app/components/pagos/pagos.component.html, visitantes/src/app/components/registrar-paqueteria/registrar-paqueteria.component.html, visitantes/src/app/components/trabajador/trabajador.component.html, visitantes/src/app/components/visita-condomino/visita-condomino.component.html
Se realizó el acomodo del menú y la corrección de la ortografía en diversos módulos.
=> se realizo el acomodo del menu y se corrigo la ortografia

visitantes/src/app/components/pagos/pagos.component.html
=> Correcion de pagos

backend/src/main/java/com/example/delparque/controllers/PaquetesController.java, visitantes/src/app/components/bitacora-trabajadores/bitacora-trabajadores.component.css, visitantes/src/app/components/bitacora-trabajadores/bitacora-trabajadores.component.html, visitantes/src/app/components/entregar-paquete/entregar-paquete.component.html, visitantes/src/app/components/entregar-paquete/entregar-paquete.component.ts, visitantes/src/app/components/registrar-paqueteria/registrar-paqueteria.component.ts, visitantes/src/app/models/paquete-page.ts, visitantes/src/app/services/paquetes.service.ts
Se arreglaron algunos problemas para poder mostrar la paginación y a su vez se agregó la paginación (de momento solo se muestran datos en la terminal, falta implementarlo en pantalla)
=> Paginacion

visitantes/src/app/app.component.html, visitantes/src/app/components/agenda-condomino/agenda-condomino.component.html, visitantes/src/app/components/menu-global/menu-global.component.html, visitantes/src/app/components/pie-pagina/pie-pagina.component.html, visitantes/src/index.html
Se creo la barra de navegacion, hace falta agregar pantallas para que esten todas agregadas, hay que verificar
=> Creacion de nav var 

visitantes/src/app/components/bitacora-trabajadores/bitacora-trabajadores.component.html, visitantes/src/app/components/entregar-paquete/entregar-paquete.component.css, visitantes/src/app/components/entregar-paquete/entregar-paquete.component.html, visitantes/src/app/components/entregar-paquete/entregar-paquete.component.ts, visitantes/src/app/models/paquete.ts, visitantes/src/app/services/paquetes.service.ts
Queda pendiente ver el diseño y algunos datos que se muestran en pantalla de paquetes
=> se arreglo la paginacion de paquetes y trabajadores

visitantes/src/app/app.component.css, visitantes/src/app/components/encabezado/encabezado.component.css, visitantes/src/app/components/encabezado/encabezado.component.html, visitantes/src/app/components/pie-pagina/pie-pagina.component.css, visitantes/src/styles.css
Cambios de estilos general , navbar y pie de pagina
=> Menu y pie de pagina responsivos

visitantes/src/app/components/agenda-condomino/agenda-condomino.component.css, visitantes/src/app/components/agenda-condomino/agenda-condomino.component.html, visitantes/src/app/components/agenda-condomino/agenda-condomino.component.ts
=> Paginacion de registro de visitas agendadas

visitantes/src/app/components/registrar-agenda/registrar-agenda.component.html
Se elimino un  lineas de codigo al momento de los problemas de la  merch
=> Resolusion de problemas de Registro Agenda

visitantes/src/app/components/trabajador/trabajador.component.css, visitantes/src/app/components/trabajador/trabajador.component.html, visitantes/src/app/components/trabajador/trabajador.component.ts
Se corrigió la validación de datos y el estilo se agregó de manera correcta, queda pendiente agregarlo a las diferentes pantallas
=> validacion de datos

visitantes/src/app/app.component.html, visitantes/src/app/components/bitacora-trabajadores/bitacora-trabajadores.component.css, visitantes/src/app/components/bitacora-trabajadores/bitacora-trabajadores.component.html, visitantes/src/app/components/menu-global/menu-global.component.html, visitantes/src/app/components/registrar-paqueteria/registrar-paqueteria.component.css, visitantes/src/app/components/trabajador/trabajador.component.css, visitantes/src/app/components/trabajador/trabajador.component.html
se adaptan a cualquier pantalla
=> Paginas de trabajadores responsivas 

visitantes/src/app/components/bitacora-trabajadores/bitacora-trabajadores.component.css, visitantes/src/app/components/bitacora-trabajadores/bitacora-trabajadores.component.html, visitantes/src/app/components/registrar-paqueteria/registrar-paqueteria.component.css, visitantes/src/app/components/registrar-paqueteria/registrar-paqueteria.component.html, visitantes/src/app/components/visita-condomino/visita-condomino.component.css, visitantes/src/app/components/visita-condomino/visita-condomino.component.html
se modifico la pagina de agendar visitantes
=> agendar visitantes responsiva

visitantes/src/app/app.component.html, visitantes/src/app/app.component.ts, visitantes/src/app/components/registrar-paqueteria/registrar-paqueteria.component.html, visitantes/src/app/components/registrar-paqueteria/registrar-paqueteria.component.ts, visitantes/src/app/components/trabajador/trabajador.component.html, visitantes/src/app/components/trabajador/trabajador.component.ts
Se crearon validacion en las pantallas de login, trabajadores y paquetes
=> validaciones

visitantes/src/app/models/condomino.ts, visitantes/src/app/models/condominoInfo.ts, visitantes/src/app/models/paquete.ts, visitantes/src/app/models/user.ts, visitantes/src/app/models/userview.ts, visitantes/src/app/models/visitante.ts
=> Modificaciones a los modelos

visitantes/src/app/components/agendar_visita_condomino/agendar_visita_condomino.component.html, visitantes/src/app/components/agendar_visita_condomino/agendar_visita_condomino.component.ts, visitantes/src/app/components/registrar-paqueteria/registrar-paqueteria.component.css, visitantes/src/app/components/registrar-paqueteria/registrar-paqueteria.component.ts, visitantes/src/app/components/registrar_trabajador/registrar_trabajador.component.html, visitantes/src/app/components/registrar_trabajador/registrar_trabajador.component.ts, visitantes/src/app/components/registrar_visitas_guardia/registrar_visitas_guardia.component.html, visitantes/src/app/components/registrar_visitas_guardia/registrar_visitas_guardia.component.ts
Se agregaron validaciones a las pantallas de Agendar visita condomino y Registrar visita, queda pendiente las validaciones en la pantalla de registrar condomino
=> validaciones a pantallas

visitantes/src/app/components/menu-global/menu-global.component.html, visitantes/src/app/components/registrar-guardia/registrar-guardia.component.css, visitantes/src/app/components/registrar-guardia/registrar-guardia.component.html, visitantes/src/app/components/registrar-guardia/registrar-guardia.component.ts
pantalla de registro de guardia añadida
=> CSS de Registro de guardia y arreglo de menu bar

visitantes/package-lock.json, visitantes/package.json, visitantes/src/app/components/reportes/reportes.component.css, visitantes/src/app/components/reportes/reportes.component.html, visitantes/src/app/components/reportes/reportes.component.ts, visitantes/src/app/services/reporte.service.spec.ts, visitantes/src/app/services/reporte.service.ts
npm install jspdf jspdf-autotable para instalar la wea de los pdf
=> Poner npm install jspdf jspdf-autotable

visitantes/src/app/components/modificacion_condomino/modificacion_condomino.component.html, visitantes/src/app/components/registrar-paqueteria/registrar-paqueteria.component.html, visitantes/src/app/components/registrar_condomino/registrar_condomino.component.html, visitantes/src/app/components/registrar_trabajador/registrar_trabajador.component.html, visitantes/src/app/components/registrar_trabajador/registrar_trabajador.component.ts, visitantes/src/app/components/registrar_visitas_guardia/registrar_visitas_guardia.component.ts
Se corrigieron unas cosas de las validaciones asi como tambien se solucionaron problemas de ortografia, Se esta trabajando en la correccion del autocompletado de los condominos en la pantalla de trabajadores
=> correcion de ortografia

visitantes/src/app/components/registrar_trabajador/registrar_trabajador.component.html
Se corrigio el error mostrado en la pantalla de registrar trabajador al momento de seleccionar un  condomino
=> Se corrigio el error de selecionar residente

visitantes/src/app/components/visitas_registradas_admin/visitas_registradas_admin.component.css, visitantes/src/app/components/visitas_registradas_admin/visitas_registradas_admin.component.html, visitantes/src/app/components/visitas_registradas_admin/visitas_registradas_admin.component.ts
Se realizo la modificación en la cual se eliminó el boton de eliminar las  visitas
=> Se elimino el boton incumplido

visitantes/src/app/app-routing.module.ts, visitantes/src/app/app.component.html, visitantes/src/app/app.component.ts, visitantes/src/app/app.module.ts, visitantes/src/app/components/modificacion_condomino/modificacion_condomino.component.html, visitantes/src/app/components/modificacion_condomino/modificacion_condomino.component.ts, visitantes/src/app/components/registrar_condomino/registrar_condomino.component.html, visitantes/src/app/components/registrar_condomino/registrar_condomino.component.ts, visitantes/src/app/components/registrar_visitas_guardia/registrar_visitas_guardia.component.ts
Se dio formato al codigo y se realizaron comentarios a los archivos
=> comentarios part 1
